### ISSUE TITLE
Add support for multiple parameters

### ISSUE THREAD

**Issue by pandasauce** [elespike/burp-cph#18]
In some cases, more than one parameter needs to be tracked. In my particular use case, it is a CSRF token and object version ID that change for each request. The sequence is:

1. Catch a request in CPH.
2. Issue another request prior to forwarding step 1.
3. Extract CSRF header value and cookies from step 2.
4. Extract additional parameter, version ID from step 2.
5. Forward step 1 with these extracted values.

This could be implemented as tabs under "parameter handling" in each tab of CPH.

**Comment by pandasauce** [comment]
For my purposes I made a hacky workaround that allows me to set up one tab to use step 2 of a different tab as extraction source. I won't be submitting a merge request because a cleaner implementation is needed. It currently uses MainTab object to store a static variable (essentially a global) with a cached request of step 2.
https://github.com/pandasauce/burp-cph/commit/b9d3c908dd69786162d13239a697e72a9468431a

**Comment by elespike** [comment]
Hi there, @pandasauce !

This is a cool use case. I'm happy to say that CPH can actually already do this at its current state, if I've understood your scenario correctly. Short demonstration gif below.

Basically:
- Check "Extender" under the Options tab so CPH can handle requests from Burp extensions (including itself). This will allow CPH to re-use the responses to its own requests (but not modify its own requests; that could be loopy).
- Create one tab to handle the token/cookies: grab the original request, and replace the token/cookie values by issuing a different request and reading from that response.
- Create an intermediate tab (which doesn't even need to be enabled) in order to cache the request/response that was issued by CPH. It's important to scope this tab to the request that will be issued by tab 1.
- Create a third tab to finally re-use the issued request/response and obtain the secondary value.

Does this fit your particular case?

![cache_issued](https://user-images.githubusercontent.com/14970655/28906229-17883158-77e4-11e7-98f0-7db21236c3c8.gif)

**Comment by pandasauce** [comment]
That worked like a charm, thanks!

**Comment by pandasauce** [comment]
On a side note, this setup allows for 2 parameters to be extracted. What about scenarios with an arbitrary number of parameters?

For example, a single form may be allowing to edit multiple objects in the application. After each form submission, updates are written to all objects in that form, and new identifiers are generated for all objects. These new identifiers need to be included for next form submission (i.e. if using intruder or active scan or making life easier in repeater). In this scenario, there could be any number of parameters that need to be tracked. Do you think something like this would be common enough to have it supported by the extension?

I may be able to find some time to implement a PoC for it later this week, but no promises.

**Comment by elespike** [comment]
As long as the number of parameters is known, you'd need at most an extra tab to modify each parameter.

Essentially:
- Tab 1 would remain the same to get the token
- Tab 2 would remain the same to cache tab 1's issued request/response
- Tab 3 would deal with the first additional parameter by using Tab 2's cache
- Tabs 4 through N can still use Tab 2's cache, so they'd deal with the second through Nth parameters exactly in the same manner as Tab 3. In other words, as long as a response has been cached in a previous tab, all subsequent tabs have access to it.

I've considered this scenario a couple times (which is why we can at least handle it, if not too gracefully) but I'm not sure that a graceful way of going about it exists.

While your suggestion of having tabs within each CPH tab is sound, wouldn't it we basically be trading extra tabs at the top for extra tabs within the tab?

**Comment by elespike** [comment]
@pandasauce good to close the issue?
