### ISSUE TITLE
Replace User-Agent RegEx with nothing doesn't work

### ISSUE THREAD

**Issue by Simon-Davies** [elespike/burp-cph#23]
See the Remove User Agent config in the screenshot. The only way to get this to work is to replace User-Agent: with Old-User-Agent:

![untitled](https://user-images.githubusercontent.com/713455/34836470-e40790a4-f6ef-11e7-8b35-4761c993314c.png)

**Comment by elespike** [comment]
Hi, @Simon-Davies!

A couple things to consider:
- I fixed a regex bug (#19) a little while ago that hasn't yet been pushed to Burp's BApp store. For now, you'll need to run the latest version from this repository.
- Even when you do use the latest version with the bug fix, here's how you would configure CPH to remove the User-Agent entirely:

![image](https://user-images.githubusercontent.com/14970655/34858210-f46859ba-f71c-11e7-9704-fa237ecff5a5.png)

This happens because CPH treats the entire HTTP request as one string, and its regular expressions don't apply to all of the lines of that string.

For example, replacing `^GET` with `HEAD` would work, but `^GET.*$` with `HEAD / HTTP/1.1` would not.

Likewise, if the last thing in your request is `Connection: close`, then replacing `close\r\n\r\n$` would work, but `^Connection.*$` would not.

I've been thinking of ways to handle Regular Expressions more intuitively, so it's possible that this will be easier to configure in the future.

**Comment by Simon-Davies** [comment]
This is now working . Thank you for your help.

**Comment by elespike** [comment]
My pleasure!
