### ISSUE TITLE
Need your help 

### ISSUE THREAD

**Issue by ba1ma0** [elespike/burp-cph#51]
Hi  Marius! First of all thank you very much for your burp-cph,it helps me a lot ! But i meet a  scenario that seems can't be solved by this burpsuite extension
Scenario description likes below:
![截屏2021-01-26 上午11 15 40](https://user-images.githubusercontent.com/32502627/105796368-a9658500-5fc9-11eb-99fd-354956801a26.png)
In this kind of scenario , how could i use this extension to issue a right request!
I read all your document,but it seems can't solve my problem!
I'm looking forward to your reply😊😊😊😊

**Comment by elespike** [comment]
Hi, @ba1ma0 

Thanks for reaching out, and I'm happy the extension has helped you =)

To clarify, are `token`, `publickey`, `challenge`, and `validate` found in the **responses** to requests 130 and 139?

If that's the case, you can target those requests for caching in order to obtain those values later for request 140:
https://github.com/elespike/burp-cph/wiki/08.-Utilizing-cached-responses

**Comment by ba1ma0** [comment]
Ok thank you very much !☺️😊

**Comment by elespike** [comment]
👍 happy to help

**Comment by pavithraasok** [comment]
Hi Marius, thank you for giving more explanation on cph.
I have an internal website which passes almost 5 parameters for login and two along the Url
Got an error while caching the first parameter as preliminary scope check negative!
Can you please help me to understand more on overcoming this?
